pages:
  stage: deploy
  script:
    - tar -zcvf ./public.tar.gz ./*
    - mkdir ./public
    - tar -zxvf ./public.tar.gz -C ./public
    - rm -rf ./public.tar.gz
  artifacts:
    paths:
      - public
  only:
    - master